version: '3.1'

services:
  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: T4ineH45l0
    volumes:
      - /opt/mysql_data:/var/lib/mysql
    ports:
      - 5000:3306
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 9000:8080
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    volumes:
      - /opt/zookeeper_data:/var/lib/zookeeper
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /opt/kafka_data:/kafka
  nifi:
    image: apache/nifi
    container_name: nifi
    ports:
      - 9999:8080
    volumes:
      - ../scrapers:/Memelysis/scrapers
      - ../hdfs:/Memelysis/hdfs
      - ../ocr:/Memelysis/ocr
      - /opt/nifi_data:/opt/nifi